

-- Question 1: What are the details of all cars purchased in the year 2022? 

SELECT * FROM cars
INNER JOIN sales ON cars.car_id = sales.car_id
WHERE Year(sales.purchase_date) = 2022;

-----------------------------------------------------------------------------------------------------------------

-- Question 2: What is the total number of cars sold by each salesperson?

SELECT salespersons.name AS salesperson_name, COUNT(sales.car_id) AS cars_sold FROM salespersons
INNER JOIN sales ON salespersons.salesman_id = sales.salesman_id
GROUP BY salespersons.name

-----------------------------------------------------------------------------------------------------------------

-- Question 3: What is the total revenue generated by each salesperson?

SELECT salespersons.name, SUM(cars.cost_$) AS Total_Revenue FROM sales
INNER JOIN cars ON sales.car_id = cars.car_id
INNER JOIN salespersons ON  sales.salesman_id = salespersons.salesman_id
GROUP BY salespersons.name;

-----------------------------------------------------------------------------------------------------------------

-- Question 4: What are the details of the cars sold by each salesperson?

SELECT sales.salesman_id, salespersons.name, cars.make, cars.style, cars.type, cars.cost_$ FROM sales
INNER JOIN salespersons ON sales.salesman_id = salespersons.salesman_id
INNER JOIN cars on sales.car_id = cars.car_id;

-----------------------------------------------------------------------------------------------------------------

-- Question 5: What is the total revenue generated by each car type?

SELECT cars.type, SUM(cost_$) FROM cars
INNER JOIN sales ON cars.car_id = sales.car_id
GROUP BY cars.type;

-----------------------------------------------------------------------------------------------------------------

-- Question 6: What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?

SELECT salespersons.name, cars.make, cars.type, cars.style, cars.cost_$, sales.purchase_date FROM cars
INNER JOIN sales ON cars.car_id = sales.car_id
INNER JOIN salespersons ON sales.salesman_id = salespersons.salesman_id 
WHERE year(sales.purchase_date) = 2021 AND salespersons.name = 'Emily Wong'

-----------------------------------------------------------------------------------------------------------------

-- Question 7: What is the total revenue generated by the sales of hatchback cars?

SELECT style AS Car_Style, SUM(cost_$) AS Total_Revenue FROM cars
INNER JOIN sales ON cars.car_id = sales.car_id
WHERE Style = 'Hatchback';

-----------------------------------------------------------------------------------------------------------------

-- Question 8:  What is the total revenue generated by the sales of SUV cars in the year 2022?

SELECT style AS Car_Style, SUM(cost_$) AS Total_Revenue FROM cars
INNER JOIN sales ON cars.car_id = sales.car_id
WHERE Style = 'SUV' AND year(purchase_date) = 2022

-----------------------------------------------------------------------------------------------------------------

-- Question 9: What is the name and city of the salesperson who sold the most number of cars in the year 2023?

SELECT salespersons.name, salespersons.city, COUNT(sales.sale_id) AS Total_cars_sold FROM salespersons
INNER JOIN sales ON salespersons.salesman_id = sales.salesman_id
WHERE year(sales.purchase_date) = 2023
GROUP BY salespersons.name, salespersons.city
ORDER BY Total_cars_sold Desc
LIMIT 1;

-----------------------------------------------------------------------------------------------------------------

-- Question 10: What is the name and age of the salesperson who generated the highest revenue in the year 2022?

SELECT salespersons.name, salespersons.age, SUM(cars.cost_$) AS Heighest_Revenue FROM salespersons
INNER JOIN sales ON salespersons.salesman_id = sales.salesman_id
INNER JOIN cars ON sales.car_id = cars.car_id
WHERE year(sales.purchase_date) = 2022
GROUP BY salespersons.name, salespersons.age
ORDER BY Heighest_Revenue Desc
LIMIT 1;

-----------------------------------------------------------------------------------------------------------------